{
  parserClass="arma.config.parser.ArmaConfigParser"
  psiPackage="arma.config.psi"
  psiImplPackage="arma.config.psi.impl"
  elementTypeHolderClass="arma.config.psi.ArmaConfigTypes"
  tokenTypeClass="arma.config.psi.ArmaConfigTokenType"

  tokens = [
    CLASS_KEYWORD = 'class'
    LBRACE = '{'
    RBRACE = '}'
    EQUAL = '='
    SEMICOLON = ';'
    LBRACKET = '['
    RBRACKET = ']'
    COMMA = ','
    COLON = ':'

    IDENT = "regex:[A-Za-z_][A-Za-z0-9_]*"
    NUMBER = "regex:\d+"
    STRING = "regex:\"([^\"\\n]|\\.)*\""
  ]
}

configFile ::= item*

private item ::= classDecl | assignment | ';'

classDecl ::= CLASS_KEYWORD IDENT LBRACE item* RBRACE SEMICOLON?

assignment ::= IDENT EQUAL value SEMICOLON

value ::= IDENT | NUMBER | STRING
